In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dell\.conda\envs\akhil\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\.conda\envs\akhil\lib\site-packages (from openpyxl) (2.0.0)

In [10]:
import pandas as pd

In [11]:
df = pd.read_excel('onedata1.xlsx')

In [4]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

# Using Pandas

In [5]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [6]:
df = pd.get_dummies(
    data=df,
    columns=['fuel', 'seller_type', 'transmission', 'owner'],
    dtype=int,
    drop_first=True
)

# With Sklearn OneHotEcoder¶
When sparse=True, the encoded output is returned as a sparse matrix, while sparse=False returns a dense matrix.

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
ohe = OneHotEncoder(
    drop='first',
    dtype=int,
    sparse_output=False
)

In [12]:
df_trf = ohe.fit_transform(
    df[['fuel', 'seller_type', 'transmission', 'owner']]
)

In [14]:
df_trf

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4340, 11))

In [15]:
cols = ohe.get_feature_names_out()

In [16]:
cols

array(['fuel_Diesel', 'fuel_Electric', 'fuel_LPG', 'fuel_Petrol',
       'seller_type_Individual', 'seller_type_Trustmark Dealer',
       'transmission_Manual', 'owner_Fourth & Above Owner',
       'owner_Second Owner', 'owner_Test Drive Car', 'owner_Third Owner'],
      dtype=object)

In [17]:
df_trf

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4340, 11))

In [18]:
pd.DataFrame(data=df_trf,columns=cols)

,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0,0,0,1,1,0,1,0,0,0,0
1,0,0,0,1,1,0,1,0,0,0,0
2,1,0,0,0,1,0,1,0,0,0,0
3,0,0,0,1,1,0,1,0,0,0,0
4,1,0,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4335,1,0,0,0,1,0,1,0,1,0,0
4336,1,0,0,0,1,0,1,0,1,0,0
4337,0,0,0,1,1,0,1,0,1,0,0
4338,1,0,0,0,1,0,1,0,0,0,0
4339,0,0,0,1,1,0,1,0,0,0,0